pub mod action;
pub mod algorithms;
pub mod board;
pub mod changer;
pub mod clues;
pub mod effects;
pub mod error;
pub mod options;
pub mod pseudo_cell;
pub mod reporter;
pub mod solver;
pub mod strategy;
pub mod technique;
pub mod timing;
pub mod deadly_rectangles;

pub use action::Action;
pub use board::{Board, Change};
pub use changer::{ChangeResult, Changer};
pub use clues::{Clues, Verdict};
pub use effects::Effects;
pub use error::Error;
pub use options::Options;
pub use pseudo_cell::PseudoCell;
pub use timing::Timings;
pub use strategy::{Strategy, Difficulty};